version: "3.5"
services:
  redis:
    image: redis:latest

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123456

  rabbitmq:
    image: rabbitmq:latest

  elasticsearch:
    image: elasticsearch:8.10.2

  did-server-dbmigrator:
    image: yongenportkey/portkey-server-dbmigrator:master
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./appsettings-dbmigrator.json:/App/appsettings.json:rw

  did-server-auth:
    image: yongenportkey/portkey-server-auth:master
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./appsettings-authserver.json:/App/appsettings.json:rw
    depends_on:
      - redis
      - rabbitmq

  did-server-silo:
    image: yongenportkey/portkey-server-silo:master
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./appsettings-silo.json:/App/appsettings.json:rw

  did-server-api:
    image: yongenportkey/portkey-server-api:master
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./appsettings-api.json:/App/appsettings.json:rw
    depends_on:
      - redis
      - rabbitmq
      - did-server-auth
      - did-server-silo

  did-server-entity:
    image: yongenportkey/portkey-server-entityeventhandler:master
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./appsettings-entityeventhandler.json:/App/appsettings.json:rw

  did-server-contract:
    image: yongenportkey/portkey-server-contracteventhandler:master
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./appsettings-contracteventhandler.json:/App/appsettings.json:rw
