version: "3.9"

name: aelf-node
services:
  standalone-testing-node:
    restart: on-failure:5
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    platform: linux/amd64
    ulimits:
      core: -1
    security_opt:
      - seccomp=unconfined
    privileged: true
    image: gldeng/aelf-groth16-10
