version: "3.5"
services:
  redis:
    image: redis:latest

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123

  did-verifier-silo:
    image: yongenportkey/portkey-verifier-silo:master
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./appsettings-silo.json:/App/appsettings.json:rw
    depends_on:
      - redis
      - mongodb

  did-verifier-api:
    image: yongenportkey/portkey-verifier-api:master
    restart: always
    environment:
      - DOTNET_ENVIRONMENT=Development
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./appsettings-api.json:/App/appsettings.json:rw
    depends_on:
      - redis
      - mongodb
